projects:
  Bounz AppSync API:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: wgjr4cyporgcnnhc7l76smu4oq
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://nc7n3r23mzdibfmcmqmepaqqcq.appsync-api.us-east-1.amazonaws.com/graphql
